---
title: "multi100_1"
author: "Tingshu Liu"
date: '2022-05-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
dat <- read.csv("1-s2.0-S1090513816301118-mmc1.csv")
```


```{r}
library(ppcor) # parcial correlation, pcor
library(lm.beta) # get the beta for regression
```

```{r}
# get the sum of miniK and DSM-5 items, respectively
dat$miniK_total <- rowSums(dat[,c(72:91)])
dat$dsm5_total <- rowSums(dat[,c(20:42)])

# get a subset 
miniK <- subset(dat, select = c('miniK_total', 'dsm5_total', 'Age'))
```

```{r}
# partial correlation between miniK and DSM5, controlling for age
pcor(miniK)
```

```{r}
# regression that predicts DSM5 from miniK, controlling for age
model1 <- lm(data = dat, dsm5_total ~ miniK_total + Age)
summary(model1)
coef1 <- lm.beta(model1)
coef1
```

```{r}
# get the sume of HKSS items
dat$hkss_total <- rowSums(dat[,c(92:113)])

# get a subset
HKSS <- subset(dat, select = c('hkss_total', 'DSM5_Total', 'Age'))
```

```{r}
# partial correlation between HKSS and DSM5, controlling for age
pcor(HKSS)
```

```{r}
# regression that predicts DSM5 from HKSS, controlling for age
model2 <- lm(data = dat, dsm5_total ~ hkss_total + Age)
summary(model2)
coef2 <- lm.beta(model2)
coef2
```


