---
title: "Life history strategies and psychopathology: the faster the life strategies, the more symptoms of psychopathology"
author: "CCBE4"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, warning=FALSE, message=FALSE, include=FALSE}
packages =  c("tidyr", "dplyr","ppcor","lavaan", "ggplot2")

if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())), 
                   repos = "http://cran.us.r-project.org")
}
invisible(lapply(packages, library, character.only = TRUE))

root.dir = "~/Dropbox/Professional/projects/quant/multi100/"
```

```{r, warning = FALSE, error = FALSE}
dat <- read.csv("Dataset.csv")
```

## 1. Original Analyses
```{r, warning = FALSE, error = FALSE}
mod.1 <- "
MiniK_Total + DSM5_Total ~ Age

MiniK_Total ~~ DSM5_Total
"

fit.1 <- sem(mod.1, data = dat, estimator = "MLR", missing = "listwise")

summary(fit.1, fit = FALSE, std = TRUE)
```

```{r, warning = FALSE, error = FALSE}
mod.2 <- "
HKSS_Total + DSM5_Total ~ Age

HKSS_Total ~~ DSM5_Total
"

fit.2 <- sem(mod.2, data = dat, estimator = "MLR", missing = "listwise")

summary(fit.2, fit = FALSE, std = TRUE)
```

## 2. Re-analysis
#### 2.1 Main Analysis
```{r, warning = FALSE, error = FALSE}
mod.1 <- "
MiniK_Total + HKSS_Total + DSM5_Total ~ Age

DSM5_Total ~~ HKSS_Total + MiniK_Total
HKSS_Total ~~ MiniK_Total
"

fit.1 <- sem(mod.1, data = dat, estimator = "MLR", missing = "listwise")

summary(fit.1, fit = FALSE, std = TRUE)
```

```{r, warning = FALSE, error = FALSE}
dat.2 <- data.frame(
  MiniK.resid = resid(lm(MiniK_Total ~ Age, data = dat)),
  HKSS.resid = resid(lm(HKSS_Total ~ Age, data = dat)),
  DSM5.resid = resid(lm(DSM5_Total ~ Age, data = dat))
)

ggplot(dat.2, aes(x = MiniK.resid, y = DSM5.resid)) + 
  geom_point() + 
  geom_smooth(method = lm) + 
  ggpubr::stat_cor(p.accuracy = 0.001, label.x.npc = 0.75) +
  labs(x = "Age-residualize MiniK", y = "Age-residualized Total Psychopathology")

ggplot(dat.2, aes(x = HKSS.resid, y = DSM5.resid)) + 
  geom_point() + 
  geom_smooth(method = lm) + 
  ggpubr::stat_cor(p.accuracy = 0.001, label.x.npc = 0.75) +
  labs(x = "Age-residualize HKSS", y = "Age-residualized Total Psychopathology")
```

#### 2.2 Sensitivity Analysis with Principle Component
```{r, warning = FALSE, error = FALSE}
pca <- psych::principal(dat[,c("MiniK_Total","HKSS_Total")])
dat$compscores <- pca$scores

mod.2 <- "
compscores + DSM5_Total ~ Age

compscores ~~ DSM5_Total
"

fit.2 <- sem(mod.2, data = dat, estimator = "MLR", missing = "listwise")

summary(fit.2, fit = FALSE, std = TRUE)
```

#### 2.3 Sensitivity Analysis with Partial Correlation Network
```{r, warning = FALSE, error = FALSE}
ppcor::pcor(dat %>%
              dplyr::select(
                Age, Bio_Sib, Half_Sib, Step_Sib, Stepparent,
                MiniK_Total, HKSS_Total, DSM5_Total, SH_Total,
                Attach_Total, Aggresion_Total
              ),
            method = "pearson") -> pCorMat
pCorMat
```
```{r, warning = FALSE, error = FALSE}
pCorMat.thresh <- ifelse(pCorMat$p.value < (0.05 / 55), pCorMat$estimate, NA)
qgraph::qgraph(pCorMat.thresh, layout = "spring")
```








