---
title: "Task 2: Life history strategies and psychopathology: the faster the life strategies, the more symptoms of psychopathology"
author: "CCBE4"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, warning=FALSE, message=FALSE, include=FALSE}
packages =  c("tidyr", "dplyr","ppcor","lavaan", "ggplot2")

if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())), 
                   repos = "http://cran.us.r-project.org")
}
invisible(lapply(packages, library, character.only = TRUE))

root.dir = "~/Dropbox/Professional/projects/quant/multi100/"
```

```{r, warning = FALSE, error = FALSE}
dat <- read.csv("Dataset.csv")
```

## 1. Re-analysis
```{r, warning = FALSE, error = FALSE}
mod.1 <- "
MiniK_Total + DSM5_Total ~ Age

DSM5_Total ~~ MiniK_Total
"

fit.1 <- sem(mod.1, data = dat, estimator = "MLR", missing = "listwise")

summary(fit.1, fit = FALSE, std = TRUE)
```









